# ─── General settings ─────────────────────────────────────────────────────────────
[settings]
cluster    = "mainnet"               # Cluster to clone from by default
accountDir = "fixtures"              # Where JSON/.so fixtures live
keypair    = "~/.config/solana/id.json"  # Upgrade authority for programs :contentReference[oaicite:3]{index=3}

# ─── Local program mappings ──────────────────────────────────────────────────────
[programs.localnet]
spl_token        = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
ata              = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
token2022        = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
serum_dex        = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
raydium_amm      = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
jupiter          = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
metadata         = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
pumpdotfun       = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
# These will be overlaid at genesis by `mucho validator` :contentReference[oaicite:4]{index=4}

# ─── Fixtures to clone ─────────────────────────────────────────────────────────────
[clone.program.spl_token]
address   = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
cluster   = "mainnet"
frequency = "always"  # re-clone any time

[clone.program.ata]
address   = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[clone.program.token2022]
address   = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[clone.program.serum_dex]
address   = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"

[clone.program.raydium_amm]
address   = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"

[clone.program.jupiter]
address   = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"

[clone.program.metadata]
address   = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[clone.program.pumpdotfun]
address   = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
